labels: ["idea", "enhancement", "galaxy-brain"]
title: "💡 [IDEA] "
body:
  - type: markdown
    attributes:
      value: |
        # 💡 Nova Ideia para GitHub Badges Mastery
        
        Compartilhe sua ideia para melhorar estratégias de conquista de badges do GitHub!
        
        ---
        
  - type: input
    id: badge-target
    attributes:
      label: 🎯 Badge Alvo
      description: Qual badge esta ideia ajudaria a conquistar?
      placeholder: "Ex: Pull Shark, DevOps Guru, Galaxy Brain..."
    validations:
      required: true
      
  - type: dropdown
    id: difficulty
    attributes:
      label: 📊 Nível de Dificuldade
      description: Como você avaliaria a dificuldade de implementação?
      options:
        - ⭐ Fácil (1-2 horas)
        - ⭐⭐ Médio (1-2 dias)
        - ⭐⭐⭐ Difícil (1 semana+)
        - ⭐⭐⭐⭐ Muito Difícil (1 mês+)
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: 📝 Descrição da Ideia
      description: Descreva sua ideia em detalhes
      placeholder: |
        Explique:
        - O que sua ideia propõe
        - Como ela ajudaria na conquista de badges
        - Benefícios esperados
        - Possíveis desafios
      value: |
        ## 🎯 Objetivo
        [Descreva o objetivo principal da ideia]
        
        ## 🛠️ Implementação
        [Como você implementaria esta ideia?]
        
        ## 🏆 Impacto nos Badges
        [Quais badges isso ajudaria a conquistar?]
        
        ## 📈 Benefícios
        - [ ] Benefício 1
        - [ ] Benefício 2
        - [ ] Benefício 3
        
        ## ⚠️ Considerações
        [Possíveis desafios ou limitações]
    validations:
      required: true
      
  - type: checkboxes
    id: implementation
    attributes:
      label: 🚀 Status de Implementação
      description: Você já começou a implementar esta ideia?
      options:
        - label: 💭 Apenas uma ideia (não implementada)
        - label: 🔬 Prototipada/testada parcialmente
        - label: 🛠️ Em desenvolvimento ativo
        - label: ✅ Implementada e funcionando
        - label: 📚 Precisa de ajuda para implementar
        
  - type: textarea
    id: examples
    attributes:
      label: 📝 Exemplos ou Código
      description: Compartilhe exemplos, código ou links relacionados
      placeholder: |
        Cole aqui:
        - Snippets de código
        - Links úteis
        - Screenshots
        - Exemplos práticos
      render: markdown
      
  - type: checkboxes
    id: collaboration
    attributes:
      label: 🤝 Colaboração
      description: Como você gostaria de colaborar nesta ideia?
      options:
        - label: 👨‍💻 Quero implementar sozinho
        - label: 🤝 Gostaria de colaborar com outros
        - label: 💡 Apenas compartilhando a ideia
        - label: 🆘 Preciso de ajuda para implementar
        - label: 📖 Posso ajudar a documentar
        
  - type: markdown
    attributes:
      value: |
        ---
        
        ## 🏆 Galaxy Brain Badge
        
        Esta discussão contribui para a conquista do **Galaxy Brain badge** através de:
        - 💡 Compartilhamento de ideias inovadoras
        - 🧠 Discussões técnicas de qualidade
        - 🤝 Colaboração na comunidade
        - 📈 Contribuição para melhorias do projeto
        
        **Obrigado por contribuir com suas ideias!** 🙏
