labels: ["question", "help-wanted", "galaxy-brain"]
title: "🙋 [Q&A] "
body:
  - type: markdown
    attributes:
      value: |
        # 🙋 Perguntas & Respostas - GitHub Badges
        
        Tire suas dúvidas sobre estratégias para conquistar badges do GitHub!
        
        ---
        
  - type: dropdown
    id: badge-category
    attributes:
      label: 🏆 Categoria do Badge
      description: Sobre qual categoria de badge você tem dúvidas?
      options:
        - 🦈 Pull Shark (Pull Requests)
        - 👥 Pair Extraordinaire (Co-autoria)
        - ⚙️ DevOps Guru (GitHub Actions)
        - 🧠 Galaxy Brain (Discussões)
        - 🎲 YOLO (Merge sem review)
        - ⚡ Quickdraw (Issues rápidas)
        - ❤️ Heart On Your Sleeve (Reações)
        - 🎯 Estratégia Geral
        - 🛠️ Implementação Técnica
        - 📊 Monitoramento de Progresso
    validations:
      required: true
      
  - type: input
    id: experience-level
    attributes:
      label: 📈 Seu Nível de Experiência
      description: Como você descreveria seu nível com GitHub?
      placeholder: "Ex: Iniciante, Intermediário, Avançado..."
    validations:
      required: false
      
  - type: textarea
    id: question
    attributes:
      label: ❓ Sua Pergunta
      description: Descreva sua dúvida em detalhes
      placeholder: |
        Seja específico sobre:
        - O que você está tentando fazer
        - Qual problema encontrou
        - O que já tentou
        - Qual resultado esperado
      value: |
        ## ❓ Pergunta Principal
        [Sua pergunta aqui]
        
        ## 📝 Contexto
        [Forneça contexto sobre sua situação]
        
        ## 🔍 O que já tentei
        - [ ] Tentativa 1
        - [ ] Tentativa 2
        - [ ] Tentativa 3
        
        ## 🎯 Resultado Esperado
        [O que você espera alcançar]
        
        ## 📋 Informações Adicionais
        [Qualquer informação adicional relevante]
    validations:
      required: true
      
  - type: checkboxes
    id: urgency
    attributes:
      label: ⏰ Urgência
      description: Qual a urgência da sua pergunta?
      options:
        - label: 🔥 Urgente (preciso de resposta hoje)
        - label: ⚡ Alta (preciso em alguns dias)
        - label: 📅 Normal (tenho tempo para aguardar)
        - label: 💭 Apenas curiosidade
        
  - type: textarea
    id: tried-solutions
    attributes:
      label: 🔧 Soluções Tentadas
      description: Descreva o que você já tentou fazer
      placeholder: |
        Liste aqui:
        - Comandos executados
        - Configurações testadas
        - Documentação consultada
        - Erros encontrados
      render: markdown
      
  - type: checkboxes
    id: help-type
    attributes:
      label: 🆘 Tipo de Ajuda Necessária
      description: Que tipo de ajuda você precisa?
      options:
        - label: 💡 Orientação conceitual
        - label: 🛠️ Ajuda técnica/código
        - label: 📚 Recursos de aprendizado
        - label: 🔍 Debugging/solução de problemas
        - label: 📈 Estratégia/planejamento
        - label: 🤝 Revisão de implementação
        
  - type: input
    id: repository
    attributes:
      label: 🔗 Repositório (opcional)
      description: Link para o repositório relacionado à pergunta
      placeholder: "https://github.com/usuario/repositorio"
    validations:
      required: false
      
  - type: markdown
    attributes:
      value: |
        ---
        
        ## 🧠 Galaxy Brain Badge Progress
        
        Fazer perguntas de qualidade contribui para o **Galaxy Brain badge**:
        - ❓ Perguntas bem formuladas
        - 🧠 Discussões técnicas valiosas
        - 🤝 Engajamento com a comunidade
        - 📈 Compartilhamento de conhecimento
        
        ## 📋 Dicas para Perguntas Eficazes
        
        1. **Seja específico**: Descreva exatamente o problema
        2. **Forneça contexto**: Explique o que está tentando fazer
        3. **Mostre o que tentou**: Liste soluções já testadas
        4. **Inclua exemplos**: Código, comandos, screenshots
        5. **Defina sucesso**: Explique o resultado esperado
        
        **Obrigado por contribuir com perguntas valiosas!** 🙏
