name: 🏆 Badge Progress Tracking
description: Track progress on achieving specific GitHub badges
title: "🏆 [BADGE] "
labels: ["badge-tracking", "progress", "quickdraw"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        # 🏆 Badge Progress Tracking
        
        Use este template para acompanhar o progresso na conquista de badges específicos.
        
        ---
        
  - type: dropdown
    id: badge-name
    attributes:
      label: 🎯 Badge Alvo
      description: Qual badge você está tentando conquistar?
      options:
        - 🦈 Pull Shark
        - 👥 Pair Extraordinaire
        - ⚙️ DevOps Guru
        - 🧠 Galaxy Brain
        - 🎲 YOLO
        - ⚡ Quickdraw
        - ❤️ Heart On Your Sleeve
        - 📊 Outro (especificar nos comentários)
    validations:
      required: true
      
  - type: dropdown
    id: current-status
    attributes:
      label: 📊 Status Atual
      description: Qual o status atual da conquista deste badge?
      options:
        - 🔄 Iniciando (0-25%)
        - 📈 Em progresso (25-50%)
        - 🚀 Avançado (50-75%)
        - 🎯 Quase lá (75-99%)
        - ✅ Conquistado!
        - ❌ Travado/Com problemas
    validations:
      required: true
      
  - type: textarea
    id: strategy
    attributes:
      label: 🛠️ Estratégia Atual
      description: Descreva sua estratégia para conquistar este badge
      placeholder: |
        Detalhe:
        - Que abordagem está usando
        - Que ferramentas/workflows implementou
        - Cronograma planejado
        - Obstáculos identificados
      value: |
        ## 🎯 Estratégia Principal
        [Descreva sua abordagem principal]
        
        ## 📋 Tarefas Planejadas
        - [ ] Tarefa 1
        - [ ] Tarefa 2
        - [ ] Tarefa 3
        
        ## ⏰ Cronograma
        - **Início:** [Data]
        - **Meta de conclusão:** [Data]
        - **Marcos importantes:** [Datas]
        
        ## 🚧 Obstáculos Identificados
        [Liste possíveis problemas ou desafios]
    validations:
      required: true
      
  - type: checkboxes
    id: requirements
    attributes:
      label: ✅ Requisitos do Badge
      description: Marque os requisitos que você já cumpriu
      options:
        - label: 📚 Entendo os critérios do badge
        - label: 🛠️ Configurei ferramentas necessárias
        - label: 📝 Criei plano de ação
        - label: ⚡ Implementei automações
        - label: 📊 Configurei monitoramento
        - label: 🧪 Testei a estratégia
        
  - type: textarea
    id: progress-log
    attributes:
      label: 📈 Log de Progresso
      description: Documente seu progresso e atualizações
      placeholder: |
        Use este espaço para:
        - Registrar marcos alcançados
        - Documentar problemas encontrados
        - Anotar soluções testadas
        - Celebrar conquistas parciais
      value: |
        ## 📅 [Data] - Log de Progresso
        
        ### ✅ Conquistas Hoje
        - 
        
        ### 🔧 Ações Realizadas
        - 
        
        ### 🚧 Problemas Encontrados
        - 
        
        ### 📅 Próximos Passos
        - [ ] 
        - [ ] 
        - [ ] 
        
        ---
        
        *Adicione novas entradas acima desta linha*
    validations:
      required: false
      
  - type: input
    id: target-date
    attributes:
      label: 📅 Data Alvo
      description: Quando você espera conquistar este badge?
      placeholder: "Ex: 2024-01-15"
    validations:
      required: false
      
  - type: checkboxes
    id: support-needed
    attributes:
      label: 🆘 Suporte Necessário
      description: Que tipo de ajuda você precisa?
      options:
        - label: 💡 Orientação estratégica
        - label: 🛠️ Ajuda técnica
        - label: 📚 Recursos de aprendizado
        - label: 🤝 Revisão de código/configuração
        - label: 📊 Ajuda com monitoramento
        - label: 🎯 Não preciso de ajuda no momento
        
  - type: markdown
    attributes:
      value: |
        ---
        
        ## 🏆 Badge Achievement Tips
        
        ### 🦈 Pull Shark
        - Crie pelo menos 2 PRs que sejam merged
        - Use branches para features/fixes
        - Documente bem suas mudanças
        
        ### 👥 Pair Extraordinaire  
        - Adicione co-autores nos commits
        - Use: `Co-authored-by: Nome <email>`
        - Demonstre colaboração real
        
        ### ⚙️ DevOps Guru
        - Configure GitHub Actions workflows
        - Implemente CI/CD pipelines
        - Automatize testes e deployments
        
        ### 🧠 Galaxy Brain
        - Participe de discussões
        - Faça perguntas valiosas
        - Responda discussões de outros
        
        ### 🎲 YOLO
        - Faça merge sem aguardar review
        - Use em mudanças de baixo risco
        - Demonstre confiança no código
        
        ### ⚡ Quickdraw
        - Crie issues rapidamente (< 5min)
        - Use automação quando possível
        - Seja eficiente na documentação
        
        ### ❤️ Heart On Your Sleeve
        - Adicione reações em issues/PRs
        - Use emojis para expressar sentimentos
        - Engaje com a comunidade
        
        ---
        
        **Esta issue contribui para:** ⚡ **Quickdraw** + ❤️ **Heart On Your Sleeve** badges!
